import seaborn as sns
import matplotlib.pyplot as plt 
import pandas as pd
df=pd.DataFrame({
   "hours": [1, 2, 3, 4, 5],
   "score": [10, 20, 30, 40, 50]
})
print(df.head())
print(df.describe())
print(df.info())
print(df["hours"].value_counts())
print(df.columns)
plt.figure(figsize=(10,6))
sns.barplot(x="hours", y="score", data=df)  
plt.title("Bar Plot of Hours vs Score")
plt.xlabel("Hours")
plt.ylabel("Score")
plt.savefig('barplot.png')
plt.close()
plt.figure(figsize=(10,6))
sns.histplot(df["score"], kde=True) 
plt.title("Histogram of Score")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.savefig('histogram.png')
plt.close()
plt.figure(figsize=(10,6))
corr=df.corr(numeric_only=True) 
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.savefig('heatmap.png')
plt.close()
sns.pairplot(df)
plt.savefig('pairplot.png')
plt.close()
plt.pie(df["hours"], labels=df["hours"], autopct='%1.1f%%')
plt.title("Pie Chart of Hours")
plt.savefig('piechart.png')
plt.close()
plt.figure(figsize=(10,6))
sns.boxplot(x="hours", y="score", data=df)
plt.title("Box Plot of Hours vs Score")
plt.xlabel("Hours")
plt.ylabel("Score")
plt.savefig('boxplot.png')
plt.close()