import seaborn as sns
import matplotlib.pyplot as plt 
import pandas as pd
df=pd.read_csv("data.csv")
print(df.head())
print(df.describe())
print(df.info())
print(df["Region"].value_counts())
print(df["Value"].value_counts())
plt.figure(figsize=(10,6))
sns.barplot(x="Region", y="Value", data=df)
plt.title("Bar Plot of Region vs Value")
plt.xlabel("Region")
plt.ylabel("Value")
plt.show()
plt.figure(figsize=(10,6))
sns.histplot(df["Value"], kde=True)
plt.title("Histogram of Value")
plt.xlabel("Value")
plt.ylabel("Frequency") 
plt.show()
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()