import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
df=pd.DataFrame({
    'month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'sales': [100, 150, 200, 250, 300, 350],
    'profit': [20, 30, 50, 70, 90, 110]
})
print(df.head())
print(df.describe())
print(df.info())
print(df["month"].value_counts())
sns.lineplot(x="month", y="sales", data=df)
plt.title("Line Plot of Month vs Sales")    
plt.xlabel("Month")
plt.ylabel("Sales") 
plt.savefig('lineplot.png')
plt.close()
sns.barplot(x="month", y="profit", data=df)
plt.title("Bar Plot of Month vs Profit")    
plt.xlabel("Month")
plt.ylabel("Profit")
plt.savefig('barplot.png')
plt.close()
sns.histplot(df["sales"], kde=True)
plt.title("Histogram of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.savefig('histogram.png')
plt.close()
sns.scatterplot(x="sales", y="profit", data=df)
plt.title("Scatter Plot of Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.savefig('scatterplot.png')
plt.close()
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
corr=df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.savefig('heatmap.png')
plt.close()
sns.pairplot(df)
plt.savefig('pairplot.png') 
plt.close()